version: "2"
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8081"
    links:
      - mongo
      - rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    environment:
      MONGODBURI: "${MONGODBURI}"
      BROKER_URI: rabbitmq
      PREFETCH_COUNT: 3
  mongo:
    container_name: user_mongo
    image: mongo
    hostname: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27017"
